import { logout, protectPage } from "./auth.js";
import { deleteExpense, generateReport, getAnalysis, getExpenses, getToday, parseExpenses, saveExpenses, setBudget, updateExpense } from "./api.js";

let pendingExpenses = [];
let editingExpenseId = null;
const money = (value) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(value || 0);
const pdfMoney = (value) => `INR ${new Intl.NumberFormat("en-IN", { maximumFractionDigits: 0 }).format(value || 0)}`;
const monthKey = () => { const now = new Date(); return `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}`; };
let analysisMonth = monthKey();
let trackMonth = monthKey();
const monthLabel = (month) => new Date(`${month}-01T00:00:00`).toLocaleDateString("en-IN", { month: "long", year: "numeric" });
const expenseDate = (expense) => (expense.expense_date || expense.created_at || "").slice(0, 10);
const dateLabel = (date) => date ? new Date(`${date}T00:00:00`).toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" }) : "Date unavailable";
const showModal = (id) => document.getElementById(id).classList.add("visible");
const hideModal = (id) => document.getElementById(id).classList.remove("visible");
const escapeHtml = (value = "") => { const div = document.createElement("div"); div.textContent = value; return div.innerHTML; };
const setLoading = (visible, text = "Loading your finances...") => { const loader = document.getElementById("appLoader"); if (loader) { document.getElementById("appLoaderText").textContent = text; loader.classList.toggle("visible", visible); } };

protectPage(async (user) => {
  const firstName = user.displayName?.split(" ")[0] || "there";
  const hour = new Date().getHours();
  document.getElementById("greeting").textContent = `${hour < 12 ? "Good morning" : hour < 17 ? "Good afternoon" : "Good evening"}, ${firstName}`;
  ["userAvatar", "menuAvatar"].forEach((id) => { document.getElementById(id).src = user.photoURL || ""; });
  document.getElementById("profileName").textContent = user.displayName || "User";
  document.getElementById("profileEmail").textContent = user.email || "";
  document.getElementById("trackMonth").textContent = monthLabel(trackMonth);
  document.getElementById("analysisMonth").value = analysisMonth;
  setupEvents();
  setLoading(true);
  try { await refreshHome(); } finally { setLoading(false); }
});

function setupEvents() {
  document.querySelectorAll(".nav-item").forEach((button) => button.addEventListener("click", async () => {
    document.querySelectorAll(".nav-item").forEach((item) => item.classList.toggle("active", item === button));
    document.querySelectorAll(".page").forEach((page) => page.classList.toggle("active", page.id === button.dataset.page));
    if (button.dataset.page === "analysisPage") { setLoading(true, "Loading analysis..."); try { await loadAnalysis(); } finally { setLoading(false); } }
    if (button.dataset.page === "trackPage") { setLoading(true, "Loading expenses..."); try { await loadHistory(); } finally { setLoading(false); } }
  }));
  document.getElementById("previousMonth").onclick = () => changeTrackMonth(-1);
  document.getElementById("nextMonth").onclick = () => changeTrackMonth(1);
  document.getElementById("openReport").onclick = openReportModal;
  document.getElementById("closeReport").onclick = () => hideModal("reportModal");
  document.getElementById("reportPeriod").onchange = updateReportFields;
  document.getElementById("generateReport").onclick = handleReport;
  document.getElementById("analysisMonth").onchange = async (event) => { analysisMonth = event.target.value || monthKey(); await loadAnalysis(analysisMonth); };
  document.getElementById("parseButton").onclick = handleParse;
  document.getElementById("importButton").onclick = () => document.getElementById("importFile").click();
  document.getElementById("importFile").onchange = handleImport;
  document.getElementById("confirmExpenses").onclick = handleSave;
  document.getElementById("closeReview").onclick = () => hideModal("reviewModal");
  document.getElementById("closeEditExpense").onclick = () => hideModal("editExpenseModal");
  document.getElementById("saveEditedExpense").onclick = handleEditSave;
  document.getElementById("editBudget").onclick = () => showModal("budgetModal");
  document.getElementById("closeBudget").onclick = () => hideModal("budgetModal");
  document.getElementById("saveBudget").onclick = handleBudget;
  document.getElementById("logoutButton").onclick = logout;
  document.getElementById("profileButton").onclick = () => document.getElementById("profileMenu").classList.toggle("visible");
  document.addEventListener("click", (event) => { if (!event.target.closest(".profile-menu, #profileButton")) document.getElementById("profileMenu").classList.remove("visible"); });
  setupVoice();
}

async function refreshHome() { await Promise.all([loadToday(), loadAnalysis()]); }
async function handleParse() {
  const input = document.getElementById("expenseInput"); const text = input.value.trim(); if (!text) return;
  const button = document.getElementById("parseButton"); button.disabled = true; button.textContent = "Understanding...";
  try { const result = await parseExpenses(text); pendingExpenses = result.expenses.map((expense) => ({ ...expense, raw_input: text })); renderReview(); showModal("reviewModal"); }
  catch (error) { alert(error.message); } finally { button.disabled = false; button.textContent = "Add expenses"; }
}
function renderReview() {
  const container = document.getElementById("reviewList"); container.innerHTML = pendingExpenses.map((expense, index) => `<div class="review-card"><div class="review-amount"><span>₹</span><input type="number" value="${expense.amount}" data-index="${index}" data-field="amount"></div><div class="review-fields"><select data-index="${index}" data-field="category">${["Food", "Shopping", "Personal Care", "Transport", "Other"].map((category) => `<option ${category === expense.category ? "selected" : ""}>${category}</option>`).join("")}</select><input value="${escapeHtml(expense.subcategory)}" data-index="${index}" data-field="subcategory"><input type="date" value="${expense.expense_date || ""}" data-index="${index}" data-field="expense_date"></div><button class="remove-expense" data-remove="${index}">×</button></div>`).join("");
  container.querySelectorAll("input,select").forEach((field) => field.addEventListener("change", (event) => { const { index, field: name } = event.target.dataset; pendingExpenses[Number(index)][name] = name === "amount" ? Number(event.target.value) : event.target.value; }));
  container.querySelectorAll("[data-remove]").forEach((button) => { button.onclick = () => { pendingExpenses.splice(Number(button.dataset.remove), 1); renderReview(); }; });
}
async function handleSave() { if (!pendingExpenses.length) return; const button = document.getElementById("confirmExpenses"); button.disabled = true; button.textContent = "Saving..."; try { await saveExpenses(pendingExpenses); pendingExpenses = []; document.getElementById("expenseInput").value = ""; hideModal("reviewModal"); setLoading(true, "Saving expenses..."); await refreshHome(); } catch (error) { alert(error.message); } finally { setLoading(false); button.disabled = false; button.textContent = "Save expenses"; } }
async function loadToday() { const data = await getToday(); document.getElementById("todayTotal"); document.getElementById("todayCount").textContent = `${data.count} ${data.count === 1 ? "expense" : "expenses"}`; renderTransactions(document.getElementById("todayExpenses"), data.expenses); }
function renderTransactions(container, expenses) { if (!expenses.length) { container.innerHTML = `<div class="empty-state"><h3>No expenses yet</h3><p>Tell Simple Finance what you spent.</p></div>`; return; } container.innerHTML = expenses.map((expense) => `<div class="transaction"><div class="transaction-icon">${categoryIcon(expense.category)}</div><div class="transaction-info"><strong>${escapeHtml(expense.subcategory)}</strong><span>${escapeHtml(expense.category)}</span><small class="transaction-date">${dateLabel(expenseDate(expense))}</small></div><strong class="transaction-amount">${money(expense.amount)}</strong><button class="edit-expense" data-edit-expense="${escapeHtml(expense.id)}" title="Edit expense">✎</button><button class="delete-expense" data-delete-expense="${escapeHtml(expense.id)}" title="Delete expense">🗑</button></div>`).join(""); container.querySelectorAll("[data-edit-expense]").forEach((button) => { button.onclick = () => openEditExpense(expenses.find((expense) => expense.id === button.dataset.editExpense)); }); container.querySelectorAll("[data-delete-expense]").forEach((button) => { button.onclick = () => handleDelete(expenses.find((expense) => expense.id === button.dataset.deleteExpense)); }); }
async function handleDelete(expense) { if (!expense || !window.confirm(`Delete ${expense.subcategory} for ${money(expense.amount)}?`)) return; try { await deleteExpense(expense.id); await refreshHome(); if (document.getElementById("trackPage").classList.contains("active")) await loadHistory(); } catch (error) { alert(error.message); } }
async function handleImport(event) { const file = event.target.files[0]; event.target.value = ""; if (!file) return; if (!window.XLSX) return alert("The spreadsheet importer is still loading. Try again."); try { const rows = XLSX.utils.sheet_to_json(XLSX.read(await file.arrayBuffer(), { type: "array", cellDates: true }).Sheets[XLSX.read(await file.arrayBuffer(), { type: "array", cellDates: true }).SheetNames[0]], { defval: "" }); pendingExpenses = rows.map((row) => ({ amount: Number(String(row.amount ?? row.Amount ?? row.AMOUNT ?? "").replace(/,/g, "")), category: ["Food", "Shopping", "Personal Care", "Transport", "Other"].includes(row.category ?? row.Category) ? (row.category ?? row.Category) : "Other", subcategory: String(row.subcategory ?? row.Subcategory ?? row.description ?? row.Description ?? "General"), expense_date: normalizeImportDate(row.expense_date ?? row.date ?? row.Date), raw_input: "Imported file" })).filter((expense) => expense.amount > 0 && expense.subcategory); if (!pendingExpenses.length) return alert("No valid rows found. Use amount, category, subcategory, and date columns."); renderReview(); showModal("reviewModal"); } catch (error) { alert("Could not read this CSV or Excel file."); } }
function normalizeImportDate(value) { if (!value) return ""; if (value instanceof Date && !Number.isNaN(value.valueOf())) return value.toISOString().slice(0, 10); const text = String(value).trim(); if (/^\d{4}-\d{2}-\d{2}$/.test(text)) return text; const parsed = new Date(text); return Number.isNaN(parsed.valueOf()) ? "" : parsed.toISOString().slice(0, 10); }
function openEditExpense(expense) { if (!expense) return; editingExpenseId = expense.id; document.getElementById("editAmount").value = expense.amount; document.getElementById("editCategory").value = expense.category; document.getElementById("editSubcategory").value = expense.subcategory; document.getElementById("editDate").value = expenseDate(expense); showModal("editExpenseModal"); }
async function handleEditSave() { const amount = Number(document.getElementById("editAmount").value); const subcategory = document.getElementById("editSubcategory").value.trim(); const expenseDateValue = document.getElementById("editDate").value; if (!editingExpenseId || !amount || amount <= 0 || !subcategory || !expenseDateValue) return alert("Complete all expense fields."); const button = document.getElementById("saveEditedExpense"); button.disabled = true; button.textContent = "Updating..."; try { await updateExpense(editingExpenseId, { amount, category: document.getElementById("editCategory").value, subcategory, expense_date: expenseDateValue }); editingExpenseId = null; hideModal("editExpenseModal"); setLoading(true, "Updating expense..."); await refreshHome(); if (document.getElementById("trackPage").classList.contains("active")) await loadHistory(); } catch (error) { alert(error.message); } finally { setLoading(false); button.disabled = false; button.textContent = "Update expense"; } }
function categoryIcon(category) { return ({ Food: "🍴", Transport: "⛽", Shopping: "🛍", "Personal Care": "✦", Other: "₹" })[category] || "₹"; }
async function loadAnalysis(month = analysisMonth) { analysisMonth = month; document.getElementById("analysisMonth").value = month; const data = await getAnalysis(month); const budgetSet = data.budget_set; document.getElementById("remaining").textContent = budgetSet ? money(data.remaining) : "Not set"; document.getElementById("monthSpent").textContent = money(data.spent); document.getElementById("monthBudget").textContent = budgetSet ? money(data.budget) : "Not set"; document.getElementById("analysisSpent").textContent = money(data.spent); document.getElementById("analysisRemaining").textContent = budgetSet ? money(data.remaining) : "Not set"; document.getElementById("budgetProgress").style.width = `${budgetSet && data.budget ? Math.min(data.spent / data.budget * 100, 100) : 0}%`; document.getElementById("categoryBreakdown").innerHTML = Object.entries(data.categories).sort((a, b) => b[1] - a[1]).map(([category, amount]) => `<div class="category-row"><span>${categoryIcon(category)} ${category}</span><strong>${money(amount)}</strong></div>`).join(""); }
function setupVoice() { const button = document.getElementById("voiceButton"); const status = document.getElementById("voiceStatus"); const Recognition = window.SpeechRecognition || window.webkitSpeechRecognition; if (!Recognition) { button.disabled = true; button.title = "Voice input is not supported in this browser"; status.textContent = "Voice input is not supported in this browser."; status.classList.add("voice-error"); return; } const recognition = new Recognition(); recognition.lang = "en-IN"; recognition.interimResults = false; recognition.maxAlternatives = 1; button.onclick = async () => { if (button.classList.contains("listening")) { recognition.stop(); return; } if (!window.isSecureContext && !["localhost", "127.0.0.1"].includes(window.location.hostname)) { status.textContent = "Voice needs HTTPS on a phone. Open the deployed Firebase Hosting URL."; status.classList.add("voice-error"); return; } try { if (navigator.mediaDevices?.getUserMedia) { const stream = await navigator.mediaDevices.getUserMedia({ audio: true }); stream.getTracks().forEach((track) => track.stop()); } recognition.start(); button.classList.add("listening"); button.textContent = "■ Stop"; button.title = "Stop listening"; status.textContent = "Listening... speak now"; status.classList.remove("voice-error"); } catch (error) { if (error.name !== "InvalidStateError") { status.textContent = error.name === "NotAllowedError" ? "Microphone access is blocked for this site. Allow it, then reload the page." : "Unable to access the microphone. Check your browser and site settings."; status.classList.add("voice-error"); } } }; recognition.onstart = () => { button.classList.add("listening"); status.textContent = "Listening... speak now"; }; recognition.onresult = (event) => { document.getElementById("expenseInput").value = event.results[0][0].transcript; status.textContent = "Got it. Review the text, then tap Add expenses."; }; recognition.onerror = (event) => { const message = event.error === "not-allowed" || event.error === "service-not-allowed" ? "Voice was blocked by this browser or site. Use HTTPS and allow microphone access." : event.error === "no-speech" ? "I did not hear anything. Tap Speak and try again." : "Voice input stopped. Tap Speak to try again."; status.textContent = message; status.classList.add("voice-error"); button.classList.remove("listening"); button.textContent = "🎙 Speak"; button.title = "Start voice input"; }; recognition.onend = () => { button.classList.remove("listening"); button.textContent = "🎙 Speak"; button.title = "Start voice input"; }; }
function openReportModal() { const current = analysisMonth; document.getElementById("reportMonth").value = current; document.getElementById("reportYear").value = current.slice(0, 4); document.getElementById("reportStart").value = `${current}-01`; document.getElementById("reportEnd").value = current === monthKey() ? new Date().toISOString().slice(0, 10) : new Date(new Date(`${current}-01T00:00:00`).getFullYear(), new Date(`${current}-01T00:00:00`).getMonth() + 1, 0).toISOString().slice(0, 10); updateReportFields(); showModal("reportModal"); }
function updateReportFields() { const period = document.getElementById("reportPeriod").value; document.getElementById("reportMonthField").style.display = period === "monthly" ? "grid" : "none"; document.getElementById("reportYearField").style.display = period === "yearly" ? "grid" : "none"; document.getElementById("reportRangeFields").style.display = period === "custom" ? "grid" : "none"; }
function reportDates() { const period = document.getElementById("reportPeriod").value; if (period === "monthly") { const month = document.getElementById("reportMonth").value; const start = `${month}-01`; const end = new Date(new Date(`${start}T00:00:00`).getFullYear(), new Date(`${start}T00:00:00`).getMonth() + 1, 0).toISOString().slice(0, 10); return { period, start_date: start, end_date: end }; } if (period === "yearly") { const year = document.getElementById("reportYear").value; return { period, start_date: `${year}-01-01`, end_date: `${year}-12-31` }; } return { period, start_date: document.getElementById("reportStart").value, end_date: document.getElementById("reportEnd").value }; }
async function handleReport() { const button = document.getElementById("generateReport"); const dates = reportDates(); if (!dates.start_date || !dates.end_date || dates.end_date < dates.start_date) return alert("Choose a valid date range."); button.disabled = true; button.textContent = "Building report..."; try { const report = await generateReport(dates); createReportPdf(report); hideModal("reportModal"); } catch (error) { alert(error.message); } finally { button.disabled = false; button.textContent = "Create PDF report"; } }
function createReportPdf(report) { const { jsPDF } = window.jspdf; const pdf = new jsPDF(); const left = 18; let y = 18; const width = 174; pdf.setTextColor(25, 35, 29); pdf.setFontSize(20); pdf.text("Simple Finance", left, y); y += 9; pdf.setFontSize(11); pdf.setTextColor(124, 135, 126); pdf.text(`INR spending report | ${report.start_date} to ${report.end_date}`, left, y); y += 14; pdf.setTextColor(25, 35, 29); pdf.setFontSize(14); pdf.text("Overview", left, y); y += 8; pdf.setFontSize(11); pdf.text(`Total spent: ${pdfMoney(report.total)}`, left, y); pdf.text(`Transactions: ${report.expense_count}`, left + 72, y); y += 14; y = drawPdfBars(pdf, "Spending by category", report.categories, left, y, width); y += 8; y = drawPdfBars(pdf, "Monthly trend", report.monthly, left, y, width); y += 8; y = writePdfList(pdf, "AI insights", report.insights.insights, left, y, width); y += 5; writePdfList(pdf, "Recommendations", report.insights.recommendations, left, y, width); pdf.save(`simple-finance-report-${report.start_date}-to-${report.end_date}.pdf`); }
function drawPdfBars(pdf, title, values, left, y, width) { if (y > 245) { pdf.addPage(); y = 18; } pdf.setFontSize(14); pdf.setTextColor(25, 35, 29); pdf.text(title, left, y); y += 8; const entries = Object.entries(values); const max = Math.max(...entries.map((entry) => Number(entry[1])), 1); entries.forEach(([label, value]) => { pdf.setFontSize(9); pdf.setTextColor(90, 100, 92); pdf.text(label, left, y); pdf.setFillColor(220, 233, 223); pdf.rect(left + 45, y - 4, width - 60, 5, "F"); pdf.setFillColor(25, 77, 56); pdf.rect(left + 45, y - 4, (width - 60) * Number(value) / max, 5, "F"); pdf.text(pdfMoney(value), left + width - 13, y, { align: "right" }); y += 8; }); return y; }
function writePdfList(pdf, title, items, left, y, width) { if (y > 245) { pdf.addPage(); y = 18; } pdf.setFontSize(14); pdf.setTextColor(25, 35, 29); pdf.text(title, left, y); y += 8; pdf.setFontSize(10); items.forEach((item) => { const lines = pdf.splitTextToSize(`• ${item}`, width); if (y + lines.length * 5 > 280) { pdf.addPage(); y = 18; } pdf.text(lines, left, y); y += lines.length * 5 + 3; }); return y; }
async function loadHistory() { const expenses = await getExpenses(); renderTransactions(document.getElementById("expenseHistory"), expenses.filter((expense) => expenseDate(expense).startsWith(trackMonth))); document.getElementById("trackMonth").textContent = monthLabel(trackMonth); document.getElementById("nextMonth").disabled = trackMonth >= monthKey(); }
async function changeTrackMonth(offset) { const current = new Date(`${trackMonth}-01T00:00:00`); current.setMonth(current.getMonth() + offset); const nextMonth = `${current.getFullYear()}-${String(current.getMonth() + 1).padStart(2, "0")}`; if (nextMonth > monthKey()) return; trackMonth = nextMonth; await loadHistory(); }
async function handleBudget() { const amount = Number(document.getElementById("budgetInput").value); if (!amount || amount <= 0) return alert("Enter a valid budget."); const button = document.getElementById("saveBudget"); button.disabled = true; button.textContent = "Saving..."; try { await setBudget(analysisMonth, amount); hideModal("budgetModal"); setLoading(true, "Updating budget..."); await loadAnalysis(analysisMonth); } catch (error) { alert(error.message); } finally { setLoading(false); button.disabled = false; button.textContent = "Save budget"; } }
